#! /usr/bin/env python3

from pygame import USEREVENT

from vector import vector

BLACK = (0, 0, 0)
GREY = (150, 150, 150)
WHITE = (200, 200, 200)
BROWN = (210, 120, 30)
DARK_BROWN = (130, 70, 20)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (200, 200, 0)
PURPLE = (200, 0, 200)

FONT_FILE = lambda: open('./DejaVuSansMono.ttf', 'rb')

ROOM_MIN_SIZE = 6
ROOM_MAX_SIZE = 12
ROOM_MAX_MONSTER = 3

PLAYER_KILL = USEREVENT + 1
LADDER_EVENT = USEREVENT + 2
BONFIRE_EVENT = USEREVENT + 3
HUD_MESSAGE = USEREVENT + 4

GAME_PIXEL_WIDTH = 960
GAME_PIXEL_HEIGHT = 540
GAME_SPRITE_WIDTH = 32
GAME_SPRITE_HEIGHT = 18
OBJECT_SIZE = min([GAME_PIXEL_WIDTH // GAME_SPRITE_WIDTH,
                   GAME_PIXEL_HEIGHT // GAME_SPRITE_HEIGHT])
GAME_BORDER_WIDTH = (GAME_PIXEL_WIDTH % OBJECT_SIZE) // 2
GAME_BORDER_HEIGHT = (GAME_PIXEL_HEIGHT % OBJECT_SIZE) // 2
GAME_CENTER = vector([GAME_SPRITE_WIDTH, GAME_SPRITE_HEIGHT]) // 2

OBJECT_SHADOW = 10
